name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd front-end/image-processing
          npm ci

      - name: Run Tests
        run: |
          cd front-end/image-processing
          npm test

      - name: Build Angular App
        run: |
          cd front-end/image-processing
          npm run build -- --configuration production
          
      - name: Create 404.html from index.html
        run: |
          cp front-end/image-processing/dist/image-processing/browser/index.html front-end/image-processing/dist/image-processing/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: front-end/image-processing/dist/image-processing/browser
          clean: true
